### ISSUE TITLE
Architect technical solution

### ISSUE THREAD

**Issue by ValeriaVG** [en-di/battery#2]
- What is the MVP tech stack for the project?
- How would tech stack look in the future?
- What should we keep in mind?
- What drawbacks can we tolerate?
- How would we deploy the project when it's ready? 
- How should we handle predictions? AI?

## Definition of done:
- [x] Tech stack is decided
- [x] Affordable hosting provider is chosen
- [x] High-level development and investigation tasks are created

**Comment by ValeriaVG** [comment]
To keep things in one place, I'll duplicate some of the ideas I voiced elsewhere.

I think using https://supabase.com/ could be a good idea due to simplicity and price.
And I really enjoy working with deno which we could deploy to supabase as well as [edge function](https://supabase.com/edge-functions) or to [deno.deploy](https://deno.com/deploy), if we decide to use [fresh framework](https://fresh.deno.dev/) for example.

**Comment by benediktschoeffmann** [comment]
Well I didn't work with either deno or supabase (yet). From a first look, supabase seems VERY comfortable, I can't say anything a about deno yet.

I already set up a "fresh" (as in the library fresh) installation and will play a little bit with it and look how I am doing.

**Comment by benediktschoeffmann** [comment]
About the prediction:
I think we should put this in a separate task because 

- it is fairly self-contained
- there are a lot more things to consider
- it is more stageable i.e. at the beginning, we can use fixed lengths and later put an AI on top of it.

**Comment by ValeriaVG** [comment]
Added #3 🙌

**Comment by ValeriaVG** [comment]
@benediktschoeffmann sounds good, you can also take a look at my personal website, I override couple of things there.
For example, I'm not a big fan of Tailwind, so I'm using emotion/css instead + handling markdown: https://github.com/ValeriaVG/valeriavg.dev

**Comment by ValeriaVG** [comment]
And of course, it's all still up for a debate, I'll be happy to try something new if it would be better

**Comment by ValeriaVG** [comment]
I've cleaned up and released CSS-in-JS plugin for fresh, it can now be used without hassle: https://github.com/en-di/fresh-emotion

**Comment by ValeriaVG** [comment]
Do we have any other suggestions regarding tech stack or should we settle for supabase + deno for now?

**Comment by tigato02** [comment]
I have team mails! (I realize now it's from GitHub) I'm ok to work with any
things my team decide. :)  But still not ready to dive...
